services:
  next-mokuro-bookshelf:
    volumes:
      - ./:/app
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    container_name: next-mokuro-bookshelf
    user: "1000"
    ports:
      - "3000:3000"
      - "9230:9229"
    environment:
      - NODE_ENV=development
      - DEBUG=engine
    env_file:
      - ./.env

  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: default
    user: "1000"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
