services:
  next-mokuro-bookshelf:
    container_name: next-mokuro-bookshelf
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    user: "1000"
    ports:
      - "3000:3000"
      - "9230:9229"
    environment:
      - NODE_ENV=development
      - DEBUG=engine
    env_file:
      - ./.env
    volumes:
      - ./src/:/app

  db:
    image: groonga/pgroonga:latest-debian-16@sha256:8c2b35074dcfc3bc01e6d23d41d196e095e470ef956991135b8fa7cff8507beb
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: default
    user: "1000"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
