services:
  next-mokuro-bookshelf:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: prod
    container_name: next-mokuro-bookshelf
    user: "1000"
    volumes:
      - ./images/:/app/private/images/
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./.env

  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: default
    user: "1000"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
