name: Build and Test Docker

on:
  push:
    branches: ["main", "prod"]
    paths:
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
      - 'prisma/**'
      - 'public/**'
      - 'tailwind.config.js'
      - 'tsconfig.json'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.css'
  pull_request:
    branches: ["main", "prod"]
    paths:
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
      - 'prisma/**'
      - 'public/**'
      - 'tailwind.config.js'
      - 'tsconfig.json'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.css'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create .env
        run: touch .env
      - name: Build the Docker image
        run: docker compose -f docker-compose.prod.yml build --no-cache --force-rm
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: cp .env.example .env
      - name: Test the Docker image
        run: docker compose -f docker-compose.prod.yml up -d
