name: Build and Test Docker

on:
  push:
    branches: ["main", "prod"]
    paths:
      - "Dockerfile"
      - "src/package.json"
      - "src/package-lock.json"
      - "src/prisma/**"
      - "public/**"
      - "src/tailwind.config.js"
      - "src/tsconfig.json"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
  pull_request:
    branches: ["main", "prod"]
    paths:
      - "Dockerfile"
      - "src/package.json"
      - "src/package-lock.json"
      - "src/prisma/**"
      - "public/**"
      - "src/tailwind.config.js"
      - "src/tsconfig.json"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4
      - name: Create .env
        run: touch .env
      - name: Build the Docker image
        run: docker compose -f docker-compose.prod.yml build --no-cache --force-rm
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4
      - name: Create .env
        run: cp .env.example .env
      - name: Test the Docker image
        run: docker compose -f docker-compose.prod.yml up -d
