---
name: ESLint

on:
  push:
    branches: ["main"]
    paths:
      - "src/.eslintrc.json"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.tsx"
  pull_request:
    branches: ["main"]
    paths:
      - "src/.eslintrc.json"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.tsx"
  schedule:
    - cron: "41 10 * * 5"

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install ESLint
        run: |
          npm install eslint@8.56.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7
        working-directory: src

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.json
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        working-directory: src
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@f09c1c0a94de965c15400f5634aa42fac8fb8f88 # v3
        with:
          sarif_file: src/eslint-results.sarif
          wait-for-processing: true
